---
baseURL: "/"
languageCode: en-us
title: Hugo Parsa Forestry Starter
module:
  imports:
  - path: github.com/themefisher/parsa-hugo
    mounts:
    - source: layouts
      target: layouts
    - source: assets
      target: assets
    - source: static
      target: static
    - source: exampleSite/static/images
      target: static/images
summaryLength: "10"
paginate: "6"
outputs:
  home:
  - HTML
  - RSS
  - JSON
params:
  plugins:
    css:
    - link: plugins/bootstrap/bootstrap.min.css
    - link: plugins/slick/slick.css
    - link: plugins/themify-icons/themify-icons.css
    js:
    - link: plugins/jQuery/jquery.min.js
    - link: plugins/bootstrap/bootstrap.min.js
    - link: plugins/slick/slick.min.js
    - link: plugins/headroom/headroom.js
    - link: plugins/instafeed/instafeed.min.js
    - link: plugins/masonry/masonry.js
    - link: plugins/reading-time/readingTime.min.js
    - link: plugins/smooth-scroll/smooth-scroll.js
    - link: plugins/search/fuse.min.js
    - link: plugins/search/mark.js
    - link: plugins/search/search.js
  logo: "/images/blogdeprueba.PNG"
  home: Home
  layout: "1"
  description: This is meta description
  preloader: true
  search: true
  author: ''
  author_image: ''
  bio: ''
  mobile: ''
  email: ''
  address: ''
  contact_form_action: ''
  google_analitycs_id: Your ID
  copyright: Copyright, Blog de prueba 2022
  instafeed:
    enable: false
    access_token: IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn
  social: []
menu:
  main:
  - name: About
    URL: about
    weight: "2"
  - name: Contact
    URL: contact
    weight: "3"
